### ISSUE TITLE
How to deploy Nest.js app using websocket?

### ISSUE THREAD

**Issue by nninnnin** [koyeb/example-nestjs#4]
Hello! I use Koyeb to deploy my Nest.js websocket(socket.io) project.

```
// events.gateway.ts
@WebSocketGateway(8080, { transports: ['websocket'], cors: true, path: '/socket' })
export class EventsGateway {
  ...
}

```

and I set koyeb portforwarding like below

![스크린샷 2023-07-28 오후 4 09 04](https://github.com/koyeb/example-nestjs/assets/34882520/722d0d86-47e5-4ab6-9a04-292719bc46dd)

But when I link this from client side, it throws error

```
// client side
export const socketIO = io("https://service-memedulecy.koyeb.app", {
  transports: ["websocket"],
  path: "/socket",
});
```

![스크린샷 2023-07-28 오후 4 11 46](https://github.com/koyeb/example-nestjs/assets/34882520/6f4dd05a-7cb5-4e63-b8a0-eb45dd2f175a)

**Comment by brmzkw** [comment]
hey!

By chance, is your application opensource? I could try to set it up and check what is going on.

**Comment by nninnnin** [comment]
Sorry for not being opensource it now, needs to be allowed by my team members..🥹 @brmzkw 

But **I fixed this issue**, using the settings like

```
// events.gateway.ts
@WebSocketGateway({ transports: ['websocket'], cors: true })
```
![스크린샷 2023-07-28 오후 4 37 53](https://github.com/koyeb/example-nestjs/assets/34882520/cc766d91-16a7-47c0-b62e-b1c1bb1c7d79)

```
// client side
export const socketIO = io("https://service-memedulecy.koyeb.app", {
  transports: ["websocket"],
});
```

I thought Koyeb app would not support the multiple ports to be opened outside per one project, so remove the settings for port 8080 I intended to use for websocket. Then it works!

Within this scenario, does Koyeb not support any other ports except 8000? or there was an missing in my last setups?

Sorry about not showing up the project codes, it contains so many private ENVs..

---

edited: if you want, even there's no envs, you can have it
https://github.com/Meme-dulecy/backend/tree/develop

**Comment by brmzkw** [comment]
Glad you could fix the issue!

I'm sorry, but I'm not sure to understand your question. In your first screenshot, you exposed two urls to two different ports: / to 8000 and /websocket to 8080. So yes, you can configure any port other than 8000 from the "advanced" section of the service page.
